# Generated by Django 4.1.4 on 2022-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.TextField(),
        ),
    ]
